// <auto-generated />
using System;
using DataAccess.Concrete.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20241220195720_mig1")]
    partial class mig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Core.Concrete.OperationClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OperationClaims");
                });

            modelBuilder.Entity("Core.Concrete.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Core.Concrete.UserOperationClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("OperationClaimId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserOperationClaims");
                });

            modelBuilder.Entity("Entities.Concrete.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CategoryId");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1872),
                            IsActive = true,
                            Name = "Elektronik",
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1871)
                        },
                        new
                        {
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1897),
                            IsActive = true,
                            Name = "Ev ve Yaşam",
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1896)
                        },
                        new
                        {
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1898),
                            IsActive = true,
                            Name = "Moda",
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1897)
                        },
                        new
                        {
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1899),
                            IsActive = true,
                            Name = "Spor ve Outdoor",
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1898)
                        },
                        new
                        {
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1900),
                            IsActive = true,
                            Name = "Kitap, Müzik, Film",
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1899)
                        },
                        new
                        {
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1901),
                            IsActive = true,
                            Name = "Anne ve Bebek",
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1900)
                        },
                        new
                        {
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1901),
                            IsActive = true,
                            Name = "Sağlık ve Kişisel Bakım",
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1901)
                        },
                        new
                        {
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1902),
                            IsActive = true,
                            Name = "Oyun ve Hobi",
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1902)
                        },
                        new
                        {
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1903),
                            IsActive = true,
                            Name = "Otomobil ve Motosiklet",
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1903)
                        },
                        new
                        {
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1904),
                            IsActive = true,
                            Name = "Ofis ve Kırtasiye",
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1904)
                        },
                        new
                        {
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1905),
                            IsActive = true,
                            Name = "Telefonlar",
                            ParentCategoryId = 1,
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1905)
                        },
                        new
                        {
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1906),
                            IsActive = true,
                            Name = "Bilgisayarlar",
                            ParentCategoryId = 1,
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1906)
                        },
                        new
                        {
                            CategoryId = 13,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1907),
                            IsActive = true,
                            Name = "Televizyon ve Ses Sistemleri",
                            ParentCategoryId = 1,
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1907)
                        },
                        new
                        {
                            CategoryId = 14,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1908),
                            IsActive = true,
                            Name = "Aksesuarlar",
                            ParentCategoryId = 1,
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1908)
                        },
                        new
                        {
                            CategoryId = 15,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1909),
                            IsActive = true,
                            Name = "Fotoğraf ve Kamera",
                            ParentCategoryId = 1,
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1908)
                        },
                        new
                        {
                            CategoryId = 16,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1910),
                            IsActive = true,
                            Name = "Akıllı Ev Ürünleri",
                            ParentCategoryId = 1,
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1909)
                        },
                        new
                        {
                            CategoryId = 17,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1911),
                            IsActive = true,
                            Name = "Tabletler",
                            ParentCategoryId = 1,
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1910)
                        },
                        new
                        {
                            CategoryId = 18,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1912),
                            IsActive = true,
                            Name = "Mobilya",
                            ParentCategoryId = 2,
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1911)
                        },
                        new
                        {
                            CategoryId = 19,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1913),
                            IsActive = true,
                            Name = "Dekorasyon",
                            ParentCategoryId = 2,
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1912)
                        },
                        new
                        {
                            CategoryId = 20,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1914),
                            IsActive = true,
                            Name = "Mutfak Gereçleri",
                            ParentCategoryId = 2,
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1913)
                        },
                        new
                        {
                            CategoryId = 21,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1914),
                            IsActive = true,
                            Name = "Temizlik Ürünleri",
                            ParentCategoryId = 2,
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1914)
                        },
                        new
                        {
                            CategoryId = 22,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1915),
                            IsActive = true,
                            Name = "Aydınlatma",
                            ParentCategoryId = 2,
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1915)
                        },
                        new
                        {
                            CategoryId = 23,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1916),
                            IsActive = true,
                            Name = "Beyaz Eşya",
                            ParentCategoryId = 2,
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1916)
                        },
                        new
                        {
                            CategoryId = 24,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1917),
                            IsActive = true,
                            Name = "Halı ve Tekstil",
                            ParentCategoryId = 2,
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1917)
                        },
                        new
                        {
                            CategoryId = 25,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1918),
                            IsActive = true,
                            Name = "Bahçe Ürünleri",
                            ParentCategoryId = 2,
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1918)
                        },
                        new
                        {
                            CategoryId = 26,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1919),
                            IsActive = true,
                            Name = "Kadın Giyim",
                            ParentCategoryId = 3,
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1919)
                        },
                        new
                        {
                            CategoryId = 27,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1920),
                            IsActive = true,
                            Name = "Erkek Giyim",
                            ParentCategoryId = 3,
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1920)
                        },
                        new
                        {
                            CategoryId = 28,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1921),
                            IsActive = true,
                            Name = "Ayakkabı ve Çanta",
                            ParentCategoryId = 3,
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1921)
                        },
                        new
                        {
                            CategoryId = 29,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1922),
                            IsActive = true,
                            Name = "Aksesuarlar",
                            ParentCategoryId = 3,
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1922)
                        },
                        new
                        {
                            CategoryId = 30,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1923),
                            IsActive = true,
                            Name = "İç Giyim",
                            ParentCategoryId = 3,
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1923)
                        },
                        new
                        {
                            CategoryId = 31,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1924),
                            IsActive = true,
                            Name = "Koşu ve Yürüyüş",
                            ParentCategoryId = 4,
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1924)
                        },
                        new
                        {
                            CategoryId = 32,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1925),
                            IsActive = true,
                            Name = "Fitness",
                            ParentCategoryId = 4,
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1925)
                        },
                        new
                        {
                            CategoryId = 33,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1926),
                            IsActive = true,
                            Name = "Outdoor",
                            ParentCategoryId = 4,
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1925)
                        },
                        new
                        {
                            CategoryId = 34,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1927),
                            IsActive = true,
                            Name = "Yüzme",
                            ParentCategoryId = 4,
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1927)
                        },
                        new
                        {
                            CategoryId = 35,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1929),
                            IsActive = true,
                            Name = "Bicycles",
                            ParentCategoryId = 4,
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1928)
                        },
                        new
                        {
                            CategoryId = 36,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1930),
                            IsActive = true,
                            Name = "Kitaplar",
                            ParentCategoryId = 5,
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1929)
                        },
                        new
                        {
                            CategoryId = 37,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1930),
                            IsActive = true,
                            Name = "Müzik CD'leri",
                            ParentCategoryId = 5,
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1930)
                        },
                        new
                        {
                            CategoryId = 38,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1931),
                            IsActive = true,
                            Name = "Film DVD'leri",
                            ParentCategoryId = 5,
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1931)
                        },
                        new
                        {
                            CategoryId = 39,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1932),
                            IsActive = true,
                            Name = "Bebek Giyim",
                            ParentCategoryId = 6,
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1932)
                        },
                        new
                        {
                            CategoryId = 40,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1933),
                            IsActive = true,
                            Name = "Bebek Oyuncakları",
                            ParentCategoryId = 6,
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1933)
                        },
                        new
                        {
                            CategoryId = 41,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1934),
                            IsActive = true,
                            Name = "Bebek Bakım Ürünleri",
                            ParentCategoryId = 6,
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1934)
                        },
                        new
                        {
                            CategoryId = 42,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1935),
                            IsActive = true,
                            Name = "Cilt Bakımı",
                            ParentCategoryId = 7,
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1935)
                        },
                        new
                        {
                            CategoryId = 43,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1936),
                            IsActive = true,
                            Name = "Saç Bakımı",
                            ParentCategoryId = 7,
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1936)
                        },
                        new
                        {
                            CategoryId = 44,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1937),
                            IsActive = true,
                            Name = "Parfümler",
                            ParentCategoryId = 7,
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1937)
                        },
                        new
                        {
                            CategoryId = 45,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1938),
                            IsActive = true,
                            Name = "Video Oyunları",
                            ParentCategoryId = 8,
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1938)
                        },
                        new
                        {
                            CategoryId = 46,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1939),
                            IsActive = true,
                            Name = "Masa Oyunları",
                            ParentCategoryId = 8,
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1939)
                        },
                        new
                        {
                            CategoryId = 47,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1940),
                            IsActive = true,
                            Name = "Otomobil Yedek Parçaları",
                            ParentCategoryId = 9,
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1939)
                        },
                        new
                        {
                            CategoryId = 48,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1941),
                            IsActive = true,
                            Name = "Motosiklet Aksesuarları",
                            ParentCategoryId = 9,
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1940)
                        },
                        new
                        {
                            CategoryId = 49,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1942),
                            IsActive = true,
                            Name = "Ofis Mobilyaları",
                            ParentCategoryId = 10,
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1941)
                        },
                        new
                        {
                            CategoryId = 50,
                            CreatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1943),
                            IsActive = true,
                            Name = "Kırtasiye Ürünleri",
                            ParentCategoryId = 10,
                            UpdatedAt = new DateTime(2024, 12, 20, 19, 57, 20, 707, DateTimeKind.Utc).AddTicks(1942)
                        });
                });

            modelBuilder.Entity("Entities.Concrete.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"), 1L, 1);

                    b.Property<bool>("ApprovalStatus")
                        .HasColumnType("bit");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPurchased")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("fotograf")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CommentId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Entities.Concrete.Customer", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Entities.Concrete.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"), 1L, 1);

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShipCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Entities.Concrete.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<short>("UnitsInStock")
                        .HasColumnType("smallint");

                    b.Property<string>("fotograf")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Entities.Concrete.Category", b =>
                {
                    b.HasOne("Entities.Concrete.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Entities.Concrete.Category", b =>
                {
                    b.Navigation("SubCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
